{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests per Minute",
   "type": "timeseries",
   "description": "Only request types received in the specified time frame will be displayed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_count{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "active_sessions_count{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Authentication Attempts per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "auth_success_count{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "auth_failure_count{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_pct{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_pct{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Sold and Failures per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_count_count{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "pizzas_sold"
    },
    {
     "expr": "rate(failed_orders_count{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "orders_failed"
    }
   ]
  },
  {
   "title": "Revenue per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_count{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "last_request_latency_ms{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "last_pizza_creation_latency_ms{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}